server:
  port: 8080

spring:
  application:
    name:
      hyeri-batch

  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:h2:tcp://localhost:1521/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  batch:
    jdbc:
      initialize-schema: always